### Get User

GET http://localhost:6001/api/user/60bebc4971e7dd0d9efaa1ac

###

GET http://localhost:6001/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAZ21haWwuY29tIiwiaWQiOiI2MGM3NmYzNDBhMjBjMTdmZTg1NTAzM2MiLCJpYXQiOjE2MjM2ODI5NjIsImV4cCI6MTYyMzY4Mzg2Mn0.d1akYm16vhNlpj9q4QO5kyHGSE95UCnhx5vKFQbZqH8

###

GET http://localhost:6001/api/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbzJAZ21haWwuY29tIiwiaWQiOiI2MGJlYmM0OTcxZTdkZDBkOWVmYWExYWMiLCJpYXQiOjE2MjMyODQyMzksImV4cCI6MTYyMzI4NzgzOX0.WMMzrB2xGkLr6-bJN_gQQ64SdeW9_myFcZet8osjwAU

### Get Scripts
GET http://localhost:6001/api/scripts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAZ21haWwuY29tIiwiaWQiOiI2MGM3NzM3ZWU5Y2U0MjgxNDIwNzNlMDAiLCJpYXQiOjE2MjM2ODM5ODcsImV4cCI6MTYyMzY4NDg4N30.UYAtQ0YOUvRC4N3kXLwFrJGi_zLGwdGzqP1FV9pnIZ4

### Add Script
POST http://localhost:6001/api/script
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAZ21haWwuY29tIiwiaWQiOiI2MGM3NzM3ZWU5Y2U0MjgxNDIwNzNlMDAiLCJpYXQiOjE2MjM2ODM5ODcsImV4cCI6MTYyMzY4NDg4N30.UYAtQ0YOUvRC4N3kXLwFrJGi_zLGwdGzqP1FV9pnIZ4
Content-Type: application/json

{
    "content": "A long thing we want to try to memorize 3"
}

### Memorize a Script
PUT http://localhost:6001/api/script/memorize/60c93a1ec3b7eb6accfd8bc1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAZ21haWwuY29tIiwiaWQiOiI2MGM3NzM3ZWU5Y2U0MjgxNDIwNzNlMDAiLCJpYXQiOjE2MjM4MDUyMzksImV4cCI6MTYyMzgwNjEzOX0.wh229jj7xPe7kBkP6Tr-9lUiavLrF7jFRcM-EB8_ZXU

### Forget a Script
PUT http://localhost:6001/api/script/forget/60c93a1ec3b7eb6accfd8bc1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAZ21haWwuY29tIiwiaWQiOiI2MGM3NzM3ZWU5Y2U0MjgxNDIwNzNlMDAiLCJpYXQiOjE2MjM4MDUyMzksImV4cCI6MTYyMzgwNjEzOX0.wh229jj7xPe7kBkP6Tr-9lUiavLrF7jFRcM-EB8_ZXU

### Delete a Script
DELETE http://localhost:6001/api/script/60c773afe9ce428142073e01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAZ21haWwuY29tIiwiaWQiOiI2MGM3NzM3ZWU5Y2U0MjgxNDIwNzNlMDAiLCJpYXQiOjE2Mjc2MTAyMzksImV4cCI6MTYyNzYxMTEzOX0.SSG4k-3ZyuD5aYd-9MnaL7z-jv0zeAQx5EG_0nOGl04

### Practice a Script
PUT http://localhost:6001/api/script/practice/60c7fb49a08d893008d11efa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAZ21haWwuY29tIiwiaWQiOiI2MGM3NzM3ZWU5Y2U0MjgxNDIwNzNlMDAiLCJpYXQiOjE2MjM4MDYzMDAsImV4cCI6MTYyMzgwNzIwMH0.bFBOA9sJzXqYGi1VjjmUI7IjiqddwmJ3LsitcmzDU9I

### Edit a Script
PUT http://localhost:6001/api/script/60c7fb49a08d893008d11efa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha2VAZ21haWwuY29tIiwiaWQiOiI2MGM3NzM3ZWU5Y2U0MjgxNDIwNzNlMDAiLCJpYXQiOjE2MjM4MDYzMDAsImV4cCI6MTYyMzgwNzIwMH0.bFBOA9sJzXqYGi1VjjmUI7IjiqddwmJ3LsitcmzDU9I
Content-Type: application/json

{
    "content": "Some edited content"
}